# Generated by Django 3.1.2 on 2020-10-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201023_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user',
            new_name='users',
        ),
    ]
