# Generated by Django 3.1.2 on 2020-10-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20201023_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='users',
            new_name='user',
        ),
    ]
