# Generated by Django 3.1.2 on 2020-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20201023_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
    ]
