# Generated by Django 3.1.2 on 2020-10-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quiz_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.SmallIntegerField(blank=True, default=60, help_text='time to be alloted on a quiz', null=True, verbose_name='Timer'),
        ),
    ]
