# Generated by Django 3.1.2 on 2020-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20201024_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Figure'),
        ),
    ]
