# Generated by Django 3.1.2 on 2020-10-31 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20201030_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='timer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
